# Dependencies
<<<<<<< HEAD
markdown:         rdiscount
pygments:         true
=======
markdown:         kramdown
highlighter:      pygments
>>>>>>> 1aaad6481cb064f31f85d519cd56e3c1799585cf

# Permalinks
permalink:        pretty

# Server
<<<<<<< HEAD
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

=======
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://getbootstrap.com
encoding:         UTF-8

>>>>>>> 1aaad6481cb064f31f85d519cd56e3c1799585cf
# Custom vars
current_version:  3.1.1
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.1.1.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.1.1/bootstrap-3.1.1-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.1.1.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
